### ISSUE TITLE
Is there a css grid that goes with this?

### ISSUE THREAD

**Issue by herent** [robflaherty/photoshop-grids#1]
A designer I work with sent me some PSDs using your grids.  I'm supposed to create a theme for a website out of them, but as far as I can tell, there is no css grid system that lines up with the widths and gutters you have?  What system should I be using?  Can this info be added?

**Comment by robflaherty** [comment]
There isn't a corresponding CSS grid framework but it should be easy to use these grid values in any variable CSS grid system.

Is there a grid framework that you normally use?

**Comment by herent** [comment]
This designer has sent us html/css using Skeleton before, but this time sent PSDs. I've also worked on modifying the 960gs markup to be responsive on a volunteer site that I've done.

On the couple sites I've done personally that were responsive, it was impossible to use a grid system with the design.

What do you use when you create designs based on these?

**Comment by robflaherty** [comment]
I tend to not use a framework and instead write my own using Less or Sass to define column/gutter width variables. If you're looking for a fast solution you should see a handful of options if you Google something like "variable CSS grid system".

**Comment by herent** [comment]
Guess it's a moot point. Just checked the desktop versions and they don't line up with the grid at all. Seems like this theme will be all custom.

I haven't really gotten into Less or Sass, either. It's on the list of things to learn, but there just hasn't been time.

Anyway, thanks for the answers.
